spring:
  config:
    activate:
      on-profile: local
  application:
    name: bankapp
  datasource:
    url: jdbc:h2:mem:banco_desafio;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  mvc:
    view:
      prefix: /templates/
      suffix: .html

server:
  error:
    whitelabel:
      enabled: false
    path: /error


