spring:
  config:
    activate:
      on-profile: homol
  application:
    name: bankapp
  datasource:
    url: jdbc:mysql://localhost:3306/banco_desafio?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
      format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

server:
  error:
    whitelabel:
      enabled: false
    path: /error

