spring:
  config:
    activate:
      on-profile: prod
  application:
    name: bankapp
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://prod-db:3306/banco_desafio?useSSL=false&serverTimezone=UTC}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:prod_user}
    password: ${SPRING_DATASOURCE_PASSWORD:prod_pass}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
      format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

server:
  port: ${SERVER_PORT:8080}
  error:
    whitelabel:
      enabled: false
    path: /error


